### ISSUE TITLE
How to pass the PerformContext to services for logging?

### ISSUE THREAD

**Issue by brentconey** [pieceofsummer/Hangfire.Console#1]
Hello,
Thank you so much for this addition to hangfire, we could really use it where I work!

The only confusion I have is with passing this PerformContext object to the actual background jobs that are running. Is this supposed to be passed with the BackgroundJob.Enqueue(() => TaskMethod(null)) call?

Seems like I can't new one up in my service when I'm doing the background tasks as the constructor takes a lot of parameters that I wouldn't have in my service, so just need some guidance on how to inject that object into my background jobs so that I can start to see some logging in the hangfire dashboard!

Thanks again for writing this, and I hope to hear from you soon!

Brent Coney

**Comment by pieceofsummer** [comment]
Yup, you should specify `null` when queuing a job, Hangfire will substitute it automatically.

**Comment by brentconey** [comment]
Awesome, thanks. Just to clarify If I am passing other arguments will that still be okay?
Example:
BackgroundJob.Enqueue(() => TaskMethod(arg1, arg2, null))

**Comment by odinserj** [comment]
@brentconey, but don't forget that there may be unprocessed jobs with the previous signature. It's better to *add* a new method, so you have the new, and the old one:

```csharp
// Old method
public void TaskMethod(int arg1, string arg2)
{
    // In this case, PerformContext will not be substituted,
    // you should add all the null-checks.
    TaskMethod(arg1, arg2, null);
}

public void TaskMethod(int arg1, string arg2, PeformContext context)
{
    // Put the logic here, 
}
```

**Comment by brentconey** [comment]
@odinserj ah, okay. good to know! Thank you!

**Comment by odinserj** [comment]
After adding a new method, yes, just call the `BackgroundJob.Enqueue(() => TaskMethod(arg1, arg2, null))`.

**Comment by brentconey** [comment]
@pieceofsummer @odinserj Thanks a ton guys!

**Comment by danr777** [comment]
Why can't I pass null in this example.....   
![image](https://user-images.githubusercontent.com/4326648/41310799-906564c0-6e50-11e8-9752-3f3cb8cf4963.png)

**Comment by pieceofsummer** [comment]
@danr777 it is not about `null`, it’s just your `TaskMethod` is an instance method, but you’re attempting to call it without class instance reference. You should either make it static, or provide an instance.

**Comment by danr777** [comment]
thanks!! oops

**Comment by paulparreno** [comment]
Why am I gettings this error?
![image](https://user-images.githubusercontent.com/38482862/43810556-e4ef3950-9aea-11e8-906a-099f47bb33ab.png)

**Comment by nicholasyin** [comment]
Having to pass PerformContext is a BAD design to me, as I'd prefer to separate any Hangfire involvement from the job itself. I believe this is a quite common requirement and real-world scenario.

**Comment by teghoz** [comment]
> Yup, you should specify `null` when queuing a job, Hangfire will substitute it automatically.

This is not working `System.ArgumentNullException: Value cannot be null.
Parameter name: Context`

**Comment by jfantunes** [comment]
Another solution a little bit more cleaner?
