### ISSUE TITLE
How to export logs to a elasticsearch?

### ISSUE THREAD

**Issue by mslagle** [pieceofsummer/Hangfire.Console#102]
Unless I go down the route of logging to both a discrete log file and the console at the same time using an extension method, I dont see a way to export the logs to elasticsearch.

Is there a real-time event I could use?  I am not sure the best way to send logs in real-time to elastic.

**Comment by FixRM** [comment]
I guess, the best way is to `.UseNLog()` with Hangfire itself and configure NLog to use NLog.Targets.ElasticSearch. But you still have to log to both places.
