### ISSUE TITLE
Doesn't show multiple progress bars

### ISSUE THREAD

**Issue by robertovaldesperez** [pieceofsummer/Hangfire.Console#105]
`public void Execute(PerformContext performContext)
        {
            var cadastreService = ApplicationContextHolder.GetApplicationContext().GetObject<ICadastreService>();

            var files = new DirectoryInfo("C:\FicherosCAT").GetFiles("prueba.gz");
            var numFiles = files.Length;
            **var progressBar = performContext.WriteProgressBar();
            progressBar.SetValue(0);**

            foreach (var fileInfo in **files.WithProgress(progressBar, files.Length)**)
            {
                using var reader = new StreamReader(new FileStream(FileUtils.Decompress(fileInfo), FileMode.Open), Encoding.UTF8);
                // Get number of estates and properties
                reader.BaseStream.Seek(-1001, SeekOrigin.End);
                var buffer = new byte[1000];

                var size = 200;
                var pageRequest = new PageRequest(1, size, new Sort() { Orders = new List<Order>() });
                var numberOfElements = 0;
                var hasNext = true;

                var context = new CadastralLineContext()
                {
                    Line = Encoding.UTF8.GetString(buffer, 0, reader.BaseStream.Read(buffer, 0, 1000)).Replace(Environment.NewLine, string.Empty).TrimStart()
                };
                CadastralLineParser.Evaluate(context);

                // Read the rest of the file
                reader.BaseStream.Seek(0, SeekOrigin.Begin);
                while (reader.Peek() >= 0)
                {
                    /*if (token.IsCancellationRequested)
                    {
                        return;
                    }*/
                    context.Line = reader.ReadLine().Replace(Environment.NewLine, string.Empty).TrimStart();

                    CadastralLineParser.Evaluate(context);
                }

                var total = context.Estates.Count();
                hasNext = total > 0;
                while (hasNext)
                {
                    var page = context.Estates.Skip(pageRequest.Offset).Take(pageRequest.Size).Where(w => w.Latitude >= ValidationUtils.MIN_LATITUDE && w.Latitude <= ValidationUtils.MAX_LATITUDE && w.Longitude >= ValidationUtils.MIN_LONGITUDE && w.Longitude <= ValidationUtils.MAX_LONGITUDE);

                    cadastreService.Load(page);

                    numberOfElements += page.Count();
                    **progressBar.SetValue(numberOfElements * 100 / total);**

                    hasNext = pageRequest.Page + 1 < (long)Math.Ceiling((decimal)total / pageRequest.Size);
                    pageRequest.Page++;
                }
                **progressBar.SetValue(100);**
            }
        }`

**Comment by pieceofsummer** [comment]
Why do you expect for it to show multiple progress bars? You're only calling `performContext.WriteProgressBar()` once.

Also mixing explicit `progressBar.SetValue()` calls and `WithProgress` wrapper for the same progress bar object is confusing. You should use either of those but not both.
