### ISSUE TITLE
Logging in .NET Core

### ISSUE THREAD

**Issue by coremcallis** [pieceofsummer/Hangfire.Console#106]
I'm using .NET Core 3.1 in my web application and Hangfire.Core v1.7.19 alongside Hangfire.Console v1.4.2 but can't find any options for UseConsole on the ConfigureServices in Startup.cs to enable the nice logging of jobs.  I just get the following without being able to trigger the use console at startup:

![image](https://user-images.githubusercontent.com/55496683/104892349-fc0bc500-5969-11eb-9e09-9d55313cf017.png)

Have the steps changed since the readme was written for newer versions?  This is the only options I'm getting:

![image](https://user-images.githubusercontent.com/55496683/105329998-b3524700-5bc9-11eb-8087-d089eb695c1c.png)

**Comment by coremcallis** [comment]
Bump...any ideas on this one please?  Haven't gotten anywhere with it

**Comment by Qpirate** [comment]
You need to include the namespace first before the Extension will appear. `using Hangfire.Console`

**Comment by coremcallis** [comment]
Don't I feel stupid now!!  🤦  Thanks
