### ISSUE TITLE
Log items can sometimes render in the wrong order.

### ISSUE THREAD

**Issue by caesay** [pieceofsummer/Hangfire.Console#13]
Hello, thanks for your wonderful work on this project.

I've ran into a strange issue where sometimes log entries appear out of order, even though their timestamps are correct. See below where "Creating new subscription..." was written at 9.321, before the previous three messages, but rendered at the end

![screen-shot](https://cloud.githubusercontent.com/assets/1287295/21641092/8a474e5e-d271-11e6-9d8e-7d6e89c4a252.png)

I can verify that the `context.WriteLine(...)` calls happened in the same order of the timestamps, and "Done." is written as the last line of the Task.

My suggested fix would be to order the output of `ConsoleRenderer.ReadLines` [here](https://github.com/pieceofsummer/Hangfire.Console/blob/master/src/Hangfire.Console/Dashboard/ConsoleRenderer.cs#L120) by timestamp.

**Comment by pieceofsummer** [comment]
Could it be you're logging from multiple threads? What kind of storage are you using?

**Comment by caesay** [comment]
The implementation of the task is a simple, single-threaded, method. It just does some synchronous http requests. It's backed onto the latest ubuntu `redis-server` package.

**Comment by pieceofsummer** [comment]
@odinserj does redis preserve the order of the records in Set, like other providers?

**Comment by odinserj** [comment]
You can use the `score` parameter for sorting purposes by setting it to a current unix timestamp in milliseconds.

**Comment by pieceofsummer** [comment]
@caesay can you please check if the issue is resolved in 1.1.7?

**Comment by caesay** [comment]
I will close for now, if the issue resurfaces on 1.1.7 I will reopen.
