### ISSUE TITLE
Nuget private API key is committed in appveyor.yml

### ISSUE THREAD

**Issue by BredStik** [pieceofsummer/Hangfire.Console#130]
The private key should be kept secret.  Anyone could publish malicious code to nuget on your behalf.  Hopefully, you have rotated your nuget api key since committing this file.

**Comment by pieceofsummer** [comment]
API keys in the yml are encrypted and tied to the appveyor account, and no one besides appveyor itself should be able to decrypt them. No worries.

**Comment by BredStik** [comment]
> API keys in the yml are encrypted and tied to the appveyor account, and no one besides appveyor itself should be able to decrypt them. No worries.

Great!  Better safe than sorry!  ;-)
