### ISSUE TITLE
clickable links for navigation?

### ISSUE THREAD

**Issue by datumgeek** [pieceofsummer/Hangfire.Console#14]
it would be cool if the links shown below were clickable :smile:

![image](https://cloud.githubusercontent.com/assets/22680176/21799182/6bc8d584-d6d5-11e6-896c-0a4d1b3bee84.png)

**Comment by pieceofsummer** [comment]
Added experimental hyperlink detection in v1.2.0, you're welcomed to try it.

Hyperlinks' markup is not stored in the database, so you're safe to rollback anytime.

**Comment by datumgeek** [comment]
will give it a go this morning :smile:

**Comment by datumgeek** [comment]
@pieceofsummer - wow is that cool !!!!!!!!!!!!!!!!

i have a job that spawns other jobs (breakdown of work).  now it is super easy to link to the sub-tasks !!!!

![image](https://cloud.githubusercontent.com/assets/22680176/22182057/8ca976aa-e058-11e6-9092-6366ed1759b1.png)

thank you so much !!!! :smile: :sparkles: :boom: :sparkles:

**Comment by accountbank** [comment]
that doesn't seem to be the case for `data:` URIs dumped, ie: `data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAAyCAYAAAD1JPH3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABZ6SURBVHhe7Z1XrB1FEoYviJyMCCZHkUROAoTJCBmRETmDABFNMkmAYQGLuAKTxBoWYYG0IJawrA0IAWKJFryY8AD7ZNA`

Wonder how much trouble it'd be to render it as an `<img>` tag in the markup. Is there any way to extend the hyperlink support that was added with additional pattern detection and rendering?
