### ISSUE TITLE
See console on failed jobs

### ISSUE THREAD

**Issue by waynebrantley** [pieceofsummer/Hangfire.Console#15]
When a hangfire job fails it gets placed in the 'Failed' job group.
If you go to that failed job and click it for details, it shows you the exception information.

It would be great if it would also show the output from the console that happened too!

Is that possible?

**Comment by pieceofsummer** [comment]
If there's a Processing state in history, console should be shown automatically.

But console is currently expired independently from the job itself (after 24 hours by default), so it may be already deleted when you check the failed job. I'm currently working on a solution for that.

**Comment by datumgeek** [comment]
Thank you for your efforts :smile: @pieceofsummer

**Comment by waynebrantley** [comment]
Unless the console data expires as soon as the job fails, this is not working.   In my case, I did a write to the console right before throwing an exception.   When on the job failure screen, it only shows the exception and not the console.  Pretty sure the console has not expired yet since the job just failed in my tests?

**Comment by pieceofsummer** [comment]
@waynebrantley do you possibly mean "Failed Jobs" list?

![screen shot 2017-01-20 at 15 54 53](https://cloud.githubusercontent.com/assets/2262364/22151914/ee8f94d4-df28-11e6-933d-76e3e5b10329.png)

Console is really not shown there, because there's no way to customize list entries. But if you click on the job id to see details, console will be there.

**Comment by waynebrantley** [comment]
Yes, sorry... I mean failed job list.
When you expand it as you show and indicate it does not show the console..that would be the ideal place to show it if possible.

As you indicate, clicking on the job brings you the full screen.  (I didn't know it even had that) So, that is at least a way to see the output since it cannot display on the 'Failed jobs' screen.
