### ISSUE TITLE
Update WriteLine Value

### ISSUE THREAD

**Issue by DR9885** [pieceofsummer/Hangfire.Console#24]
There are certain cases I'd like to update a console write. Weather it's printing out multiple parallel states of multiple processes, or even just printing out a "Current/Total" Count (ex: 24/30,000).

Is there anyway I can do this with the current lib?

**Comment by pieceofsummer** [comment]
Nope.

Pseudo-updating of the value is only supported for progress bars. "Pseudo," because the value is not actually updated, but the final value for the line is aggregated from multiple actual records.
