### ISSUE TITLE
Console not displaying messages

### ISSUE THREAD

**Issue by cleitontortato** [pieceofsummer/Hangfire.Console#25]
Hi,
I'm using on Hangfire console 1.3.0 with Hangfire 1.6.9, I'm using MySql storage but console is not displayed on Job Details.

My startup:

```
            GlobalConfiguration.Configuration
                .UseStorage(new MySqlStorage("HangFireMySqlContext"))
                .UseConsole(new ConsoleOptions { ExpireIn = TimeSpan.FromDays(30) });


            var dashboardOptions = new DashboardOptions();
            dashboardOptions.Authorization = new[] { new HangFireAuthorizationFilter() };
            app.UseHangfireDashboard("/hangfire" , dashboardOptions);
            app.UseHangfireServer(new BackgroundJobServerOptions { WorkerCount = 3 });

            HangfireServices services = new HangfireServices();
            services.StartDownload();
            services.StartParse();
            services.StartSend();

```
I tried to turn-off cache for all application in this way:

`public class FilterConfig
    {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new OutputCacheAttribute
            {
                VaryByParam = "*",
                Duration = 0,
                NoStore = true,
            });
        }
    }`

I check the records are properly stored on "set" table in my database but I had no display on Job Details, sometimes when I reset my database and re-start deployment the first time of job execution display console but not on the next scheduled times.

Looking to Chrome Developer Tools \ Network, I can see no \hangfire\console requests

Do you have some idea to fix it ?

**Comment by pieceofsummer** [comment]
Requests to `/hangfire/console` endpoint are only made when the job is still processing (i.e `Processing` is the current state), so no requests is okay for already completed jobs.

First of all, take a look at page source to see if there is `<div class="console" data-id="...">` present. There should be one (for each processing state) if the console renderer is registered correctly.

Then take `data-id` value and check if Set table really has items for that key.

**Comment by cleitontortato** [comment]
Hi, 
I found this on my Job Details page:

`<div class="console" data-id="38a56dfca511"><div class="line-buffer" data-n="-1"></div></div>`

and I found 88 records in SET table with the command bellow:

```
SELECT * FROM `set` 
where `key` like '%38a56dfca511%'
order by id desc;
```

I already check SET table and all records are stored properly, any suggestion ?

PS.: Thanks for your fast answer

**Comment by pieceofsummer** [comment]
Ok, now please check corresponding job state in `state` table if it has `StartedAt` equal to `2017-03-15T02:40:16.003 UTC`

**Comment by cleitontortato** [comment]
On `state` I found a record with Processing on `Name `column and `Data `bellow:

`{"StartedAt":"2017-03-15T02:40:16.0034048Z","ServerId":"sacramento:2328:11d00936-71d5-4bd6-bdc5-d8da0f717cd4","WorkerId":"cfab4281-30da-475a-afc0-2296ab5a6c9c"}`

**Comment by pieceofsummer** [comment]
Hm, looks totally fine to me.

Seems like I'll need to install mysql and check it out :(
Which MySql package do you use? I can find at least two of them on GitHub.

**Comment by cleitontortato** [comment]
I'm working with  `5.6 MySQL Community Server`

**Comment by pieceofsummer** [comment]
No, I mean hangfire storage package - Hangfire.MySql or Hangfire.MySqlStorage? And what version?

**Comment by cleitontortato** [comment]
Sorry, here is the right information: 

`<package id="Hangfire.MySqlStorage" version="1.0.3" targetFramework="net452" />`

**Comment by pieceofsummer** [comment]
It'd take some time for me to check it out. Meanwhile you may try another package (Hangfire.MySql 0.0.7) to see if the issue reproduces there as well.

**Comment by cleitontortato** [comment]
Ok, I'll try this another package and back here when done (maybe in 2 days)

**Comment by pieceofsummer** [comment]
@cleitontortato got any chance to look into this?

**Comment by cleitontortato** [comment]
Hi, I had a chance but with no success than I came back to `Hangfire.MySqlStorage` (seems to me a more mature project). How `Hangfire.Console` build keys using the datetime, sound's to me a issue in `DateTime` resolution on MySql database or some Collate/Localization configs. How can I run Hangfire.Console in debug, I already tried with no success in Visual Studio 2017

**Comment by pieceofsummer** [comment]
It turned out to be a bug in MySqlStorage package. Both `GetRangeFromList` and `GetRangeFromSet` are returning invalid (often empty) results because of incorrect row ranking.

I'll submit them a pull request if I manage to fix it.

**Comment by pieceofsummer** [comment]
@cleitontortato you may try this now https://github.com/arnoldasgudas/Hangfire.MySqlStorage/pull/24

**Comment by arnoldasgudas** [comment]
Fix released at https://www.nuget.org/packages/Hangfire.MySqlStorage/

**Comment by pieceofsummer** [comment]
Nice. The issue can be closed now, I suppose.
