### ISSUE TITLE
How can I get the PerformContext?

### ISSUE THREAD

**Issue by superqbb** [pieceofsummer/Hangfire.Console#27]
I created a demo task like this.
```
    public static class DataMaintainTask
    {
        public static void DemoTask(PerformContext context)
        {
            // create progress bar
            var progress = context.WriteProgressBar();
            // update value for previously created progress bar
            progress.SetValue(100);
        }
    }
````

But,how can I add the task to hangfire? I Use the following method will get an error.
I don't know how to get the PerformContext.

````
RecurringJob.AddOrUpdate("some-id", () => DataMaintainTask.DemoTask(), Cron.Hourly);
````

![image](https://cloud.githubusercontent.com/assets/3818131/24132214/c33529b8-0e2e-11e7-81ec-20b12c151804.png)

**Comment by pieceofsummer** [comment]
And here I was, hoping that the line in Readme was enough 🙂
> **NOTE**: Like `IJobCancellationToken`, `PerformContext` is a special argument type which Hangfire will substitute automatically. You should pass `null` when enqueuing a job.
