### ISSUE TITLE
liblog?

### ISSUE THREAD

**Issue by vip32** [pieceofsummer/Hangfire.Console#3]
this is really a wonderful addition to hangfire. great work!
maybe it makes sense to also write the log entries to liblog. so they appear in our normal logs too.

**Comment by pieceofsummer** [comment]
There are too many concerns here. 
Which logger should it write to? What logging level should it use? How to write progress bar updates? etc.

Why not just define an extension method which would forward message to both?

**Comment by vip32** [comment]
logger abstraction is nicely handled by liblog (hangfire uses that internally too). loglevel could be set in console options. progress bars, maybe leave that out for now.

but you are right, a custom extension method could do the same.

**Comment by pieceofsummer** [comment]
> logger abstraction is nicely handled by liblog

I mean, it is still bound to some class, which we may not know inside extension. 
For example, job is defined as interface method, which is resolved from DI container at runtime. Then console writes will be directed to logger for interface, while the remaining logging will use logger for concrete class. Stack backtrace is also a bad option, as it is expensive, and might be not available on some platforms, and may even not contain a caller job (for example, Task continuation from IO completion thread).

**Comment by waynebrantley** [comment]
Yes, I agree @pieceofsummer I do sometimes write it to the console and to the log if needed.  Separate concerns IMO.
