### ISSUE TITLE
Can't see console

### ISSUE THREAD

**Issue by jhon50** [pieceofsummer/Hangfire.Console#30]
GlobalConfiguration.Configuration.UseSqlServerStorage("DefaultConnection").UseConsole();
app.UseHangfireDashboard();
app.UseHangfireServer();

is there anything wrong with the way I'm doing it?
I can only see the console in the Processing Tab?
You said if I use dashboard and server separately I should call on both, how to do that?

**Comment by pieceofsummer** [comment]
Are your jobs writing something to console? The console won't appear in dashboard unless there's something written into it.

**Comment by jhon50** [comment]
Yeah I have this             RecurringJob.AddOrUpdate(() => Console.WriteLine("Powerful!"), "* * * * *");

**Comment by pieceofsummer** [comment]
You should call `WriteLine` on `PerformContext` object, which is passed as job parameter, as specified in readme file.

**Comment by jhon50** [comment]
Thanks! It worked.
