### ISSUE TITLE
Style not working on Chrome (Version 57.0.2987.133 (64-bit))

### ISSUE THREAD

**Issue by rav84** [pieceofsummer/Hangfire.Console#33]
Style works on IE and Firefox but when I see the site on chrome it shows as:
![image](https://cloud.githubusercontent.com/assets/2221809/25274271/2c4a5fde-2687-11e7-8d19-c2f053535254.png)

I dont think this is right.

I must add that I checked and there are no errors in the Chrome console. Doing quick inspect tells that some CSS styles are not applied in chrome for example margin-right: 20px on the span where time is displayed.

**Comment by pieceofsummer** [comment]
It looks like caching issue. Try clearing cache, or force-reloading the page.

**Comment by barrettg** [comment]
I had this issue as well, and the force reload fixed it.  You might want to include this tip in the README for others.
