### ISSUE TITLE
WriteLine using ElectStateContext ?

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [pieceofsummer/Hangfire.Console#34]
Is there a way to access the ConsoleContext from the OnStateElection method of a JobFilterAttribute?

I'd like to log to the Console actions taken when a job failed, for retrospective purposes, so that I can view the actions in the Hangfire Dashboard Console.

I appreciate any help you can provide!

**Comment by pieceofsummer** [comment]
No, this is not possible. Please refer to #28 for detailed explanation.

**TL;DR**: Console is bound to a job state, which is undefined during state election.
