### ISSUE TITLE
For any job, the last successful call to WriteLine seems to be ignored, using redis backend.

### ISSUE THREAD

**Issue by brad-jones** [pieceofsummer/Hangfire.Console#35]
Given the following example job:

```c#
public async Task Execute(PerformContext ctx, IJobCancellationToken cancellationToken)
{
    var things = await _dataContext.Things.ToListAsync();

    foreach (var thing in things)
    {
        cancellationToken.ThrowIfCancellationRequested();
        Thread.Sleep(TimeSpan.FromSeconds(1));
        ctx.WriteLine($"Do something with the thing: {thing.id}");
    }
}
```

For arguments sake lets say there were 5 things in the database.
Well I would only ever see 4 lines in the Hangfire Console output.

If I run the task like this:

```c#
public async Task Execute(PerformContext ctx, IJobCancellationToken cancellationToken)
{
    var things = await _dataContext.Things.ToListAsync();

    foreach (var thing in things)
    {
        cancellationToken.ThrowIfCancellationRequested();
        Thread.Sleep(TimeSpan.FromSeconds(1));
        ctx.WriteLine($"Do something with the thing: {thing.id}");
    }

    ctx.WriteLine();
}
```

I now see all 5 lines, the 6th line is however ignored. For now my workaround is to just call a blank WriteLine directly after every other call to WriteLine, the output is now spaced out of course but at least I see everything I expect to see.

Any ideas?

**Comment by pieceofsummer** [comment]
Which redis storage provider are you using? Is it Hangfire.Pro.Redis, or Hangfire.Redis.StackExchange, or a legacy Hangfire.Redis?

**Comment by brad-jones** [comment]
StackExchange

**Comment by pieceofsummer** [comment]
Sorry, cannot reproduce it within a template .net core app with Hangfire 1.6.14, Hangfire.Redis.StackExchange 1.7.0 and Hangfire.Console 1.3.3.

Startup.cs:
```c#
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHangfire(config =>
            {
                config.UseRedisStorage("127.0.0.1:6379,defaultDatabase=2,allowAdmin=true,syncTimeout=15000");
                config.UseConsole();
            });
        }

        public static async Task Execute(PerformContext ctx, IJobCancellationToken cancellationToken)
        {
            var things = new[] { 1, 2, 3, 4, 5 };

            foreach (var thing in things)
            {
                cancellationToken.ThrowIfCancellationRequested();
                Thread.Sleep(TimeSpan.FromSeconds(1));
                ctx.WriteLine($"Do something with the thing: {thing}");
            }
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHangfireDashboard();
            app.UseHangfireServer();

            app.Run(async (context) =>
            {
                BackgroundJob.Enqueue(() => Execute(null, null));
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }
```

Result:
<img width="856" alt="screen shot 2017-07-06 at 17 49 23" src="https://user-images.githubusercontent.com/2262364/27917110-bb1e1c32-6273-11e7-882e-b7c050166216.png">

Can you provide some more details on your environment?

**Comment by brad-jones** [comment]
Ok fair enough, I'll setup a testable example and send you the repo details.
Might take me a couple of days to get it done.
Thanks very much for your efforts thus far.

**Comment by brad-jones** [comment]
I setup a local environment and like yourself was unable to replicate the issue. In production we are running on AWS with an RDS instance of Redis.

After playing with some of the Redis timeout settings (https://stackexchange.github.io/StackExchange.Redis/Configuration) I managed to get it to work as expected.

Increasing the "SyncTimeout" value from 1 second to 10 seconds has solved the issue for me.
10 seconds is probably a little excessive and with more testing and tweaking and I imagine I'll be able to drop that value back down significantly.

**Comment by DDFM** [comment]
Can reproduce it within a template .net core app with Hangfire 1.6.20, Hangfire.Redis.StackExchange 1.7.2 and Hangfire.Console 1.4.1.

Startup.cs:
`public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHangfire(config =>
            {
                config.UseMemoryStorage();
                //config.UseRedisStorage("127.0.0.1:6379,password=123", new RedisStorageOptions { Prefix = "hangfire:drgs:" });

                config.UseConsole();
            });
        }

        public static async Task Execute(PerformContext ctx, IJobCancellationToken cancellationToken)
        {
            var things = new[] { 1, 2, 3, 4, 5 };

            foreach (var thing in things)
            {
                cancellationToken.ThrowIfCancellationRequested();
                Thread.Sleep(TimeSpan.FromSeconds(1));
                ctx.WriteLine($"Do something with the thing: {thing}");
            }
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHangfireDashboard();
            app.UseHangfireServer();

            app.Run(async (context) =>
            {
                BackgroundJob.Enqueue(() => Execute(null, null));
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }`
