### ISSUE TITLE
Wrong order of the logs

### ISSUE THREAD

**Issue by testos944** [pieceofsummer/Hangfire.Console#36]
When using PerformContext.WriteLine, the logs are often in the wrong order.

![console-wrong-log-order](https://user-images.githubusercontent.com/22033728/28009374-8b866408-655b-11e7-8f2a-7d2545478c86.png)

Current Setup : 

- Hangfire 1.6.14
- Hangfire.Console 1.3.3
- Hangfire.Mongo 0.4.0 
- Mongo Version : 3.0.12 on Windows

It seems okay when the first log appears, however when the job is finished it gets moved to the end of the paragraph.

It used to be on any log, however I can't seem to reproduce at the moment, now it's usually the first log that changes position.

**Comment by pieceofsummer** [comment]
This is a bug in the latest Hangfire.Mongo implementation. There's no SortBy instruction when returning range from Set/List, so MongoDB may return records in random order.

**Comment by testos944** [comment]
Thanks. I will create an issue on the Hangfire.Mongo page then.
