### ISSUE TITLE
Urls with query string not parsed correctly for the console

### ISSUE THREAD

**Issue by rholand3** [pieceofsummer/Hangfire.Console#37]
I am attempting to write a Url to the console using 
`context.WriteLine("http://myhost/api?param1=abc&param2=xyz")`

but in the console the html rendered is
`<a target="_blank" rel="nofollow" href="http://myhost/api?param1=abc&amp;">http://myhost/api?param1=abc&amp;</a>;param2=xyz`

I believe this has to do with ConsoleRender line 92 doing an HtmlEncode before detecting links

**Comment by pieceofsummer** [comment]
Should be fixed now. Thanks for reporting.
