### ISSUE TITLE
With Progress, could auto create a bar

### ISSUE THREAD

**Issue by DR9885** [pieceofsummer/Hangfire.Console#39]
Simple Request, can this project add a WithProgress option without a progress bar?

`
        public static async Task WithProgress<T>(this PerformContext performContext, IEnumerable<T> rows)
        {
            var bar = performContext.WriteProgressBar();
            rows.WithProgress(bar, rows.Count());
        }
`

**Comment by pieceofsummer** [comment]
Added in 1.3.5
