### ISSUE TITLE
Routes.Append

### ISSUE THREAD

**Issue by vip32** [pieceofsummer/Hangfire.Console#4]
nice, you now made it easy to modify hangfire internal css/js resources.
made use of that (DashboardRoutes.Routes.Append) to finally make a dark themed dashboard
available here: https://github.com/vip32/Hangfire.Dashboard.Dark

**Comment by pieceofsummer** [comment]
Great, glad it helped :)

A few thoughts: 
- Circles around badges are hardly seen.
- White text seems too white. I'd rather dim it a little, so it would be more comfortable to read.

But that's just my taste :)

**Comment by vip32** [comment]
thx for the feedback. colors now have been adjusted a bit (circles/whites).
