### ISSUE TITLE
Logging double, until refresh

### ISSUE THREAD

**Issue by wernerbarnard** [pieceofsummer/Hangfire.Console#40]
Haai,

So i'm using Hangfire.Console, and while keeping the page open looking at the realtime updates (amazing) - it's logging all entries twice for some reason.  see below:

![image](https://user-images.githubusercontent.com/6905546/30097487-2b7df99e-92de-11e7-96dd-c9d6590ddf1e.png)

If I refresh the page, the doubles are gone - so it only happens for new entries whilst I keep the page open.

This is the logging call:
```

            // set color according to "level"
            context.SetTextColor(
                // warning
                level == LogLevel.Warning 
                    ? ConsoleTextColor.DarkYellow 
                    // error OR critical
                    : level == LogLevel.Error || level == LogLevel.Critical 
                        ? ConsoleTextColor.Red 
                        // Trace
                        : level == LogLevel.Trace 
                            ? ConsoleTextColor.Gray 
                            // Info/Debug
                            : ConsoleTextColor.White
            );

            context.WriteLine($"{msg}");
            context.ResetTextColor();
```

Any ideas if this is a bug or an issue on my side?

**Comment by pieceofsummer** [comment]
What storage are you using?

**Comment by wernerbarnard** [comment]
Haai,
SqlServer storage.


		

		
	





On Wed, Sep 6, 2017 at 3:39 PM +0200, "Alexey Skalozub" <notifications@github.com> wrote:












What storage are you using?

**Comment by pieceofsummer** [comment]
Cannot reproduce your issue. My setup:

Test.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.6.15" />
    <PackageReference Include="Hangfire.Console" Version="1.3.4" />
    <PackageReference Include="Hangfire.Core" Version="1.6.15" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.6.15" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
  </ItemGroup>
</Project>
```

Startup.cs:
```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddHangfire(options =>
        {
            options.UseSqlServerStorage("server=.;database=Hangfire;integrated security=true");
            options.UseConsole();
        });
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddConsole();

        app.UseHangfireDashboard();
        app.UseHangfireServer();

        app.Run(async (context) =>
        {
            await context.Response.WriteAsync("Hello World!");
        });

        BackgroundJob.Enqueue(() => TestTask(null));
    }

    public static void TestTask(PerformContext context)
    {
        for (int i = 0; i < 100; i++)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            context.SetTextColor((i % 2) == 0 ? ConsoleTextColor.White : ConsoleTextColor.Yellow);
            context.WriteLine("Progress @ {0}", i);
            context.ResetTextColor();

            Thread.Sleep(2000);
        }
    }
}
```

Result:
<img width="727" alt="screen shot 2017-09-07 at 18 05 59" src="https://user-images.githubusercontent.com/2262364/30170475-e414a326-93f7-11e7-8902-362061adaf19.png">

Can you please provide a minimal project to reproduce your issue?

**Comment by wernerbarnard** [comment]
Haai,

2 Notable differences:
- im targeting 2.0 and not 1.1
- my recurring jobs / background server is running in a console app, whilst the dashboard is in a seperate basic core .net app

Would that make a difference?

**Comment by pieceofsummer** [comment]
1. Targeting 2.0 doesn't make any difference.
2. Running server and dashboard in two separate processes shouldn't make any difference as well (since data is read from the storage anyway), but I haven't actually tested it.

**Comment by wernerbarnard** [comment]
Haai,

So on the page and in dev tools, i see these 2 suspect parts:

![image](https://user-images.githubusercontent.com/6905546/30201229-3c217184-947a-11e7-9780-7d21a1b7fcbd.png)

![image](https://user-images.githubusercontent.com/6905546/30201236-43a6a050-947a-11e7-9fe9-bc201a85331f.png)

So look likes it's just double requesting, that's probably why it's not double when I refresh, only on live update.  What could be causing that?

**Comment by pieceofsummer** [comment]
Having two equal requests is okay in case the first one returned an empty update (with `data-n` value equal to `start` query parameter), so the next one picks from the same place. And there should be a 1 sec interval between them, but I can't see that on the cropped screenshot.

But having two "polling was started" messages looks suspicious, as it only should be at most one after page reload. Do you have javascript console preserved across page reloads?

Can you please provide timeline and responses for a few network requests with the same start value?

**Comment by wernerbarnard** [comment]
Hi @pieceofsummer 

not 100% sure what you're asking for, but here's more about those requests:

![image](https://user-images.githubusercontent.com/6905546/30475376-e8f8dc1c-9a06-11e7-8aef-9a5011de10bd.png)

![image](https://user-images.githubusercontent.com/6905546/30475383-f11a4de0-9a06-11e7-9e9e-0db982ab6530.png)

![image](https://user-images.githubusercontent.com/6905546/30475389-f5a11e16-9a06-11e7-80ba-57426a630f5d.png)

**Comment by wernerbarnard** [comment]
Hi @pieceofsummer 

I noticed now and found it interesting that not all line items are duplicated, but the polling - see here 2 items very close to each other was duplicated:

![image](https://user-images.githubusercontent.com/6905546/30483202-54ba8b34-9a26-11e7-82b0-2a2eb04fbbdd.png)

**Comment by pieceofsummer** [comment]
Looking at the waterfall graph, it really seems like there are duplicate requests for some reason. Can you try emptying browser cache / try another browser?

**Comment by wernerbarnard** [comment]
Same in other browsers, that i've never had this open in before - FF, Edge, Opera

**Comment by pieceofsummer** [comment]
Mad guess: can it be you’re accidentally calling UseConsole() twice during initialization?

**Comment by wernerbarnard** [comment]
Haai,

Yeah, almost thought I was being retarded.... I had it twice, 

once:
```

            services.AddHangfire(c =>
            {
                //c.UseConsole();
            });
```

And:

```
            GlobalConfiguration.Configuration.UseConsole();
```

.... but I removed the first one from the above, but it still does the same as before.

**Comment by pieceofsummer** [comment]
Now you need to clear browser cache once again, because it has already cached a “double” version of js.

**Comment by wernerbarnard** [comment]
Yeah, so guess I am a retard after all !

It works now, thanks!

The reason I have the 2nd GlobalConfig-based one is because that exists in a seperate library that is shared between the thin/bare basics web project and the one running the background server - so that the configuration is (supposed to be) the same, as I have a lot of other stuff in there....

Oh well, all sorted, thanks!

**Comment by pieceofsummer** [comment]
I think I will add a guard against calling `UseConsole` twice in the next version.
