### ISSUE TITLE
Named progress Bar

### ISSUE THREAD

**Issue by a-karpov-parc** [pieceofsummer/Hangfire.Console#41]
Can I give a name to the ProgressBar? 
Several processes are performed and each carries a named. Each process has its own ProgressBar 
![template](https://user-images.githubusercontent.com/15727500/30379810-c36cbedc-98a8-11e7-8267-ce3762c01948.png)

**Comment by pieceofsummer** [comment]
Not the way the progress bars are currently handled. 

As a workaround, you can simply write a text line with a name before the progress bar, like:
```
context.WriteLine("Total:");
var totalBar = context.WriteProgressBar();
context.WriteLine("Persistent:");
var persistentBar = context.WriteProgressBar();
```

**Comment by a-karpov-parc** [comment]
That's exactly what I did. Results on the screen: first the title, and below progressBars ))))))

**Comment by pieceofsummer** [comment]
Just added support for named progress bars in 1.3.6. You can test it as soon as it gets indexed on NuGet.

**Comment by a-karpov-parc** [comment]
YOU ARE BIGMAN!!!!!) senx!
