### ISSUE TITLE
Newtonsoft.Json version

### ISSUE THREAD

**Issue by mortenbock** [pieceofsummer/Hangfire.Console#46]
Hello.

Would you consider changing the dependency requirements for Newtonsoft.Json to match Hangfire.Core for .Net 4.5?

The core has this dependency:
Newtonsoft.Json (>= 5.0.0)

**Comment by pieceofsummer** [comment]
Hangfire.Core itself has an invalid Newtonsoft.Json reference, which gives warnings during build. The minimum existing version of Newtonsoft.Json >=5.0.0 is actually 5.0.1.

The netstandard1.3 version of Hangfire.Core references Newtonsoft.Json >= 9.0.1, and I don’t see any good reason to downgrade the dependency for net4.5 only.

Could you please elaborate on why you need to use such an old Newtonsoft.Json version?

**Comment by mortenbock** [comment]
@pieceofsummer I have a separate dependency that has a dependency of

Newtonsoft.Json (>= 4.5.11 && < 6.0.0)

So I am using Newtonsoft.Json v 5.0.8 in my application.

**Comment by mortenbock** [comment]
The specific dependency I have is UmbracoCms v 6.2.6

https://www.nuget.org/packages/UmbracoCms.Core/6.2.6

I'm not able to upgrade that, so I hope to avoid conflict if Hangfire.Console could settle for a 5.x Newtonsoft.Json

**Comment by pieceofsummer** [comment]
Ok, try v1.3.9.

**Comment by mortenbock** [comment]
That worked. Thank you very much :)
