### ISSUE TITLE
Orphaned console rows in Set table

### ISSUE THREAD

**Issue by mortenbock** [pieceofsummer/Hangfire.Console#47]
Hi

I'm using a global filter `.UseFilter(new AutomaticRetryAttribute { Attempts = 0, LogEvents = true })` on my jobs.

When a job fails, it goes to the "Failed" section on the dashboard. At this time, the `console:xxxx` rows in the `Set` sql table have a null `ExpireAt` value. 

When I delete the job from the dashboard, the `ExpireAt` is still null.

It seems that this results in the rows never getting cleaned up? I had 2 million `console:xxx` rows in the table.

If the job fishes succesfully, then the `ExpireAt` gets a value.

Do I need to do something differently to get the rows cleaned up automatically? Or should I make my own job that cleans them on a regular basis?

**Comment by mortenbock** [comment]
In the `ConsoleApplyStateFilter` this code is in the `OnStateApplied`:

            if (context.OldStateName != ProcessingState.StateName)
            {
                // Job was not in 'Processing' state, ignore.
                return;
            }

But that does not take into account the flow for Processing => Failed => Deleted.

I think that means that if a job is failed, and then deleted from the dashboard, then the `ExpireAt` is never set for the Set and Hash table rows? Is that correct?

**Comment by pieceofsummer** [comment]
Yeah, you're right. Fixed in 1.3.10.

**Comment by mortenbock** [comment]
Thank you. That fixed the issue.
