### ISSUE TITLE
Color of console

### ISSUE THREAD

**Issue by waynebrantley** [pieceofsummer/Hangfire.Console#5]
This overload does not work.
context.WriteLine("This is a test Green message", ConsoleTextColor.Green);

**Comment by pieceofsummer** [comment]
It was never supposed to work that way, as it is hard to tell whether the argument is a color or a format string parameter.

**Comment by waynebrantley** [comment]
Yeah..make sense...just took it and was happy, so thought it was an issue!
Great library....works perfectly and exactly what I needed.
