### ISSUE TITLE
css styles not working

### ISSUE THREAD

**Issue by ArgeKumandan** [pieceofsummer/Hangfire.Console#52]
Hey,
I am using hangfire version 1.6.17.0. I've followed all the steps.  Eveything works fine i see the logs but the design is not well. I've downloaded the source code and found the css file. Then i referenced it in browser console. Now eveything works fine. But it is just temporarily. Then I had to append a line which adds the style.css to the body html. Recompiled the project and referenced it manually. Until you fix the issue :)

**Comment by ArgeKumandan** [comment]
Wow. how can i not know that as a web developer 👎  You are right but i think you should've notice this as  note. We just instsall the package and follow the rules. And suddenly nothing works fine. So we just think that's a backend problem because what we do is here a whole backend process.

**Comment by pieceofsummer** [comment]
Added a note to readme.
