### ISSUE TITLE
Support for hyperlinks

### ISSUE THREAD

**Issue by shorbachuk** [pieceofsummer/Hangfire.Console#53]
Is there a way to provide a hyperlink in the console output?

Currently seems to be rendered as a literal.

**Comment by pieceofsummer** [comment]
Anything prefixed with `http(s)://` or `ftp://` (or starting with `www.` or `ftp.`) should be rendered as one. Can you please provide an example which is not rendered correctly?

**Comment by shorbachuk** [comment]
Oh ok, didn’t know that I was writing out an <a> tag which was coming out as a literal. Thank you
