### ISSUE TITLE
Context.writeline for array or List<string>

### ISSUE THREAD

**Issue by shorbachuk** [pieceofsummer/Hangfire.Console#56]
Can we have an override that accepts a string array or List<string> and prints the collection out, one line per item?

**Comment by pieceofsummer** [comment]
You can write your own extension method for whatever kind of arguments you need. It is not even required to be defined in the same assembly.

But I feel that it is a quite taste-specific case. One would like to print them one line per item, the other prefers comma- or semicolon-separated values, and someone would like a bullet list at all.

So I’d rather add neither of those, leaving anyone the opportunity to write it the way they want, using the existing basic overloads..
