### ISSUE TITLE
How to use with MediatR?

### ISSUE THREAD

**Issue by mgordic** [pieceofsummer/Hangfire.Console#59]
Hi,

Is it posible to use console withing MediatR handler?

I am able to enque a job to call MediatR handler, but I can't manage it to work to provide instance of PerformContext there.

Any ideas?

Thank you
Marko

**Comment by pieceofsummer** [comment]
I have no idea what MediatR is :)

But after a quick look at it, it is probably possible to use Console from the handler if you pass PerformContext as a part of each TRequest/TNotification.
