### ISSUE TITLE
Progress bar enhancement

### ISSUE THREAD

**Issue by waynebrantley** [pieceofsummer/Hangfire.Console#7]
Many times when using a progress bar, we are in a for-each loop.   
Looks something like this:

```
int pos=0;
int max=6200;
var bar=PerformContext.WriteProgressBar();
foreach (var item in collection)
{
   SomeWork();
   pos++
   bar.SetPos(pos/max*100);
}
```

Given that is such a common pattern, perhaps a simple enhancement would have it also work like this:

```
var bar=PerformContext.WriteProgressBar(6200);  (pass in the max)
foreach (var item in collection)
{
   SomeWork();
   bar.IncRelativePos();
}
```

Where the progress bar instance maintains the state, etc.   ( Additionally, this would enable a feature where the progress bar shows est time remaining instead of % complete - since it could track how long it has been and has all other info needed)

**Comment by pieceofsummer** [comment]
I've been thinking of an extension method on `ICollection` to track progress in `foreach` enumerations:
```
var bar = context.WriteProgressBar(); // leave it as is
foreach (var item in collection.WithProgress(bar))
{
    SomeWork(item);
}
```
So it will automatically track enumeration, and jump to 100% when enumeration ends (either normally, or as a result of `break` instruction). What do you think?

As of estimated time, need to give it a thought. I feel it would be counter-intuitive to show *remaining* time on the left (growing) side of progress bar, as it actually indicates *already passed* time/percentage, and showing it on the right (shrinking) side of a progress bar would require some changes in html layout.

**Comment by waynebrantley** [comment]
The extension on ICollection woulod work - and could use an interface like I have given above to get it done.   Still need the lower level interface in case it is an array, etc.

Estimated time - that would wait until at least 1 second had passed and then do an estimate based on how many are left.   The progress bar would be like an install...that says 1 min 20 sec remaining...etc.

One other thing.  When using the progress bar, if there are a huge number of items to process and the process is rather slow...it sits at 0% or other numbers later for a really long time.   Thought about two progress bars for this.  One that is the overall job and one that uses something like ```bar.SetPos(pos % 100)```.  Perhaps could do something better?  However, if the progress bar knew the max and I was just incrementing (or using ICollection extension), it could display a little worker bar that just moves a tick every time and then starts over.....??

**Comment by pieceofsummer** [comment]
I'm likely going to change progress bar value to `float` with 1 or 2 fractional digits instead of `int`. Even though displayed percentage will be still integer, but the progress bar movement will be more smooth this way. That would solve the issue with a huge number of items.

**Comment by waynebrantley** [comment]
Agree on the huge.  Thx.

**Comment by pieceofsummer** [comment]
Please try version 1.1.4, it adds WithProgress() extension method and fractional percentage.

**Comment by waynebrantley** [comment]
If I have an array, still in the same boat.
Any consideration of 
var bar=PerformContext.WriteProgressBar(6200);  (pass in the max)...where the max simply defaults to 100 (which is what it does now)

and 

bar.IncRelativePos();  that increments the position and sends in position/max*100 to setvalue?

**Comment by waynebrantley** [comment]
The way we use the product, I need a couple more overloads.
Generally we have 'commands'.  These commands take a PerformContext in so it can write to console using your product.  All good.

However, the PerformContext is not interface based, so we cannot easily mock it out for testing our commands.   This means in our commands we use it like this:
```command.PerformContect?.WriteProgressBar();
  command.PerformContect?.WriteLine("some log");
```
etc.

This makes it problematic to use it like this because the bar may be null, and your extension does not like that:
```
var bar = context.WriteProgressBar(); // leave it as is

foreach (var item in collection.WithProgress(bar))
{
    SomeWork(item);
}
```

So, we made some quick extensions to help with that.  It turns out these are actually better in a way - as generally you create the progressbar just so you can pass it in to WithProgress.  So, we made an overload that will make the progressbar itself.

Would you consider adding these to your library?

```
public static IEnumerable<T> WithProgress<T>(this IEnumerable<T> enumerable, PerformContext context, int count = -1)
{
    if (context == null)
        return enumerable;
    var progressBar = context.WriteProgressBar();

    return enumerable.WithProgress(progressBar, count);
}
public static IEnumerable WithProgress(this IEnumerable enumerable, PerformContext context, int count = -1)
{
    if (context == null)
        return enumerable;
    var progressBar = context.WriteProgressBar();

    return enumerable.WithProgress(progressBar, count);
}
```

**Comment by pieceofsummer** [comment]
Actually it is not too hard to mock `PerformContext`, see https://github.com/pieceofsummer/Hangfire.Console/blob/master/tests/Hangfire.Console.Tests/ConsoleExtensionsFacts.cs#L89

But you are right, it would be better to allow calling all extension methods with `null` context. This way, extra extension methods would be unnecessary, right?

**Comment by waynebrantley** [comment]
Nice on perform context....my purpose for mocking it would be so it is just not used - as I am not testing the reporting part of the command.   So, doing the null propagation is better in this case I think.

You could allow calling with null context...however I think the extra extension methods provide a cleaner syntax and no docs required to say 'you can pass null' etc...     You have an issue with the additional extensions?

**Comment by pieceofsummer** [comment]
I just think that adding those two methods "as is", without changing existing extension methods, will still be a little counter-intuitive. Since they allow null `PerformContext` (while `IProgressBar` overloads require non-null value), it will require mentioning if nulls are allowed in documentation anyways.

What's more important about your extension methods, they may behave differently in tests and in real life. Consider your collection being an `IEnumerable` of unknown size, and you forgot to specify `count` parameter. Tests will successfully pass (since `context` is `null`), but actual execution will throw an exception.

In the end, they will be like this:
```c#
public static IEnumerable WithProgress(this IEnumerable enumerable, PerformContext context, int count = -1)
{
    return enumerable.WithProgress(context?.WriteProgressBar(), count);
}
```
I have a little doubt if such one-liners will be actually useful.

**Comment by waynebrantley** [comment]
> What's more important about your extension methods, they may behave differently in tests and in real life. Consider your collection being an IEnumerable of unknown size, and you forgot to specify count parameter. Tests will successfully pass (since context is null), but actual execution will throw an exception.

As far as your library goes - your extensions suffer from the same thing.
As far as me testing my items - I am not interested in testing performcontext related things in my commands...that is just gravy.

Anyway, whatever you decide - I already have these extensions exactly as I posted them in my local solution and they are perfect what what we need - thought you might want to add for others.

Thanks!

**Comment by pieceofsummer** [comment]
>  your extensions suffer from the same thing.

Sure, but they will consistently fail both in tests and at runtime, so it can be noticed and fixed early on. Your extension methods, on the other hand, will mask the issue during tests (because of not calling original `WithProgress` when `context` is null), and it will only appear at runtime, so you'd better be careful about it.

**Comment by waynebrantley** [comment]
Right, I am not interested in trying to test the display of progress messages.

**Comment by pieceofsummer** [comment]
Even if you're not interested in progress messages, you're still altering the control flow by suppressing validations inside `WithProgress`.

Anyway, after updating to v1.1.5 you may drop all those `?.` and null checks.

**Comment by waynebrantley** [comment]
Ok, thanks.  100% of our use cases - use your new progress WithProgressBar extensions...and only create the progress bar for that extension....so we prefer our extension that creates the progress bar for us.

Thanks!
