### ISSUE TITLE
No output in .net core app

### ISSUE THREAD

**Issue by plenteum** [pieceofsummer/Hangfire.Console#72]
Hi, I'm using hangfire.console in a asp.net core 2.1 app and context.WriteLine("") and context.WriteProgressBar() do not produce any output in the dashboard. 
I'm using LiteDB Sotorage - not sure if this may be related?
Any advice would be appreciated.

**Comment by plenteum** [comment]
Definately to do with the LiteDB Storage Wrapper - Switching to Memory Storage, this is no longer an issue

**Comment by StevenDeRoover** [comment]
I'm having the same problem.  I actually do want to use LiteDB :-/

**Comment by SacuL** [comment]
Also interested in using LiteDB.
