### ISSUE TITLE
Can't see logging in dashboard when using nested functions

### ISSUE THREAD

**Issue by dotnetshadow** [pieceofsummer/Hangfire.Console#8]
Hi there,

I have the following code:

```
// Old method
public void TaskMethod()
{
    TaskMethod(arg1, arg2, null);
}

public void TaskMethod(PeformContext context)
{
     context.WriteLine("MyTask Starting");
     /// do something
     context.WriteLine("MyTask Finished");
}
```

If I call the following method, I do not see any output, even though the task works and I can see the output on the console window, but not on the dashboard

```
RecurringJob.AddOrUpdate(jobId, () => Jobs.TaskMethod(), Cron.Minutely);
```

If I call with null everything works as normal

```
RecurringJob.AddOrUpdate(jobId, () => Jobs.TaskMethod(null), Cron.Minutely);
```

In the documentation you mention that HangFire substitutes the null does do I have to do something differently if I don't want to pass null from my program calling code?

**Comment by pieceofsummer** [comment]
Hangfire substitutes null with a PerformContext when it calls the task method, but it knows nothing of any calls your method does internally, so there's no any substitutions possible there – if you pass null, it will get null. Hence, there's nothing logged.

There's nothing you can do without a valid PerformContext, as Hangfire.Console needs it for logging. You may try to make it the last argument with default null value, so it will look like there's no argument specified, but you need to check if Hangfire supports optional arguments first. I've never tried it actually, so I'm just speculating here.

**Comment by dotnetshadow** [comment]
Thanks for your explanation, as it turns out HangFire doesn't support optional arguments I did try doing that. Was just trying to make my methods as clean as possible but I guess I will need to have the PerformContext in all my methods.
