### ISSUE TITLE
Please add support for Hangfire.LiteDB

### ISSUE THREAD

**Issue by AnderssonPeter** [pieceofsummer/Hangfire.Console#89]
I love this solution, but i can't get it to work with `Hangfire.LiteDB`, i need some sort of storage medium that can work in a docker container without a additional process and Hangfire.LiteDB fits the bill as the Hangfire.SQLite does not seem to be updated any more.

I get no exception when I do the write but no console shows up in the job.

**Comment by bbakermmc** [comment]
I was looking for the same things, I dont need to persist jobs, just want a simple way to enqueue some jobs and have some basic debugging.  I was going to use LiteDB with hangfire as well.

**Comment by felixclase** [comment]
> Provider-agnostic: (allegedly) works with any job storage provider (currently tested with SqlServer and MongoDB).

This solution is agnostic to the storage used.

Hangfire.LiteDB had a bug that did not allow using this plugin.

Reference: https://github.com/codeyu/Hangfire.LiteDB/pull/17/commits/841f4e4974f3f2ac6c093a703bd36910b75fb021

Wait for version 0.3.0 to use this plugin. Reference: 
https://github.com/codeyu/Hangfire.LiteDB/milestone/1

**Comment by felixclase** [comment]
The **v0.3.0** version is already available, please try again . @AnderssonPeter @bbakermmc

**Comment by felixclase** [comment]
![image](https://user-images.githubusercontent.com/1153361/68612714-85d12000-0493-11ea-9187-d8f053f4c4aa.png)

Testing **Hangfire.Console** in **v0.3.0**

**Comment by pieceofsummer** [comment]
Looks like it is working now, so I’m closing the issue.

I believe there’s still a race condition in LiteDB distributed lock implementation, but it is not directly related to Console :)
