### ISSUE TITLE
Console output not visible when application deployed

### ISSUE THREAD

**Issue by newsoftinc** [pieceofsummer/Hangfire.Console#9]
I can see output from the console on my dev. environment. But I see no console output once deployed in my development IIS server.

Any idea ?

**Comment by pieceofsummer** [comment]
Hmm, cached js/css?
Not calling UseConsole() in IIS and/or worker?

**Comment by newsoftinc** [comment]
Not sure, dashboard was available only locally from the server. I just implemented dashboard authorization filter, republished and ensured cache is cleared and now seems to work..

Thanks.

**Comment by pieceofsummer** [comment]
Ok, glad it was resolved. I'm closing the issue then.
