### ISSUE TITLE
No console visible, empty set table

### ISSUE THREAD

**Issue by Bert-Proesmans** [pieceofsummer/Hangfire.Console#93]
Hi! Thank you for the useful extension.

I'm using the latest hangfire release in combination with the EntityCore storage provider (Pomelo adapter for MariaDB). I also use the JobActivator override to inject objects and PerformContext from my Windsor container.
The code in itself works without printed errors/warnings, but i expected the console to be visible on the job detail page.

I found #25 and followed along to debug. 
* There are console divs on the job detail page.
* The Set table ("hangfireset", as specified by the provider) is empty!

It's possible that the implementation of the storage provider isn't 100% completed, but i'd like to know in which functions/files i need to look before opening a PR.

This extension worked perfectly before when i was using the mysql storage provider directly. It stopped working after codebase consolidation efforts, sadly. It would be great if i could get this working again.

Thank you in advance!

**Comment by pieceofsummer** [comment]
My guess is HangfireSet's `Value` size is too small. It is defined to be 100 characters long, while Console expects it to be least 256 characters. Try writing some short messages and see if it works.

HangfireHash also limits `Value` length to 100 characters, so long values won't work even as references. Other storage implementations support storing values of arbitrary length in Hash table.

Is there something in HangfireHash table? It should have `jobId` rows if console context was initialised for the jobs.

**Comment by Bert-Proesmans** [comment]
Hi, thanks for the swift reply!

You are correct, both hagfireset-Key and hangfireset-Value are defined to be max 100 characters. 
All my console messages are very short <=30 characters.

The hangfirehash table is empty though. If this means my setup code is broken i cannot see how it would fail.

```csharp
public Lazy<ConsoleOptions> ConsoleOptions { get; }

        public void MakeGlobal(bool useConsole = false)
        {
            var conf = GlobalConfiguration.Configuration
                .UseRecommendedSerializerSettings()
                .UseStorage(JobStorage.Value);

            if (useConsole == true)
            {
                conf.UseConsole(ConsoleOptions.Value);
            }
        }

        private ConsoleOptions GetConsoleOptions()
        {
            return new ConsoleOptions()
            {
                ExpireIn = TimeSpan.FromHours(72),
                FollowJobRetentionPolicy = true,
            };
        }
```

```csharp
_hangfireConfiguration.MakeGlobal(useConsole: true);

var options = new BackgroundJobServerOptions()
{
     Activator = HangfireConfiguration.BuildWindsorJobActivator(_container),
     FilterProvider = _hangfireConfiguration.JobFilters.Value,
};
_server = new BackgroundJobServer(options);
```

I use instances to carry hangfire configuration data and make these global before any job server (server side) start or job enqueue (client side).
Next, I use a custom activator for windsor usage. This activator is almost verbatim the code from https://github.com/BredStik/HangFire.Windsor/blob/cd0abe8e99440ac1ac9168ffa241f058981b8df1/HangFire.Windsor/WindsorJobActivator.cs, with the exception of the actual instantiation code where i perform
```csharp
public override JobActivatorScope BeginScope(PerformContext context)
{
     return NewScope(context);
}

protected virtual WindsorJobActivatorScope NewScope(PerformContext ctxt)
{
    return new WindsorJobActivatorScope(this, ctxt, _container.BeginScope());
}

public object ActivateJob(Type jobType, PerformContext ctxt)
{
    return _container.Resolve(jobType, new Arguments().AddTyped(ctxt));
}
```

I came to a point where i have no ideas left, other than rebuilding the code from scratch, and hopefully someone else could point out my mistake.

**Comment by pieceofsummer** [comment]
I think the problem is here:
> FilterProvider = _hangfireConfiguration.JobFilters.Value

Console registers its filters in `GlobalJobFilters.Filters` which is handled by default filter provider, but probably not by your custom one.

**Comment by Bert-Proesmans** [comment]
That might be it, i'll test soon

**Comment by Bert-Proesmans** [comment]
You are right, i forced my own filters without incorporating the globally defined ones. I removed my own code and it works.
Thanks for the help!
